substitutions:
  server_url: "http://192.168.1.123:80" #http://192.168.1.119:4567
  mqtt_broker_ip: "192.168.1.100"
  manual_ip_static_ip: "192.168.1.222"
  manual_ip_gateway: "192.168.1.1"
  manual_ip_subnet: "255.255.255.0"
  name: "trmnl"
  friendly_name: "TRMNL"
  status_led: GPIO2
  button: GPIO32
  adc_pin: GPIO34
  deep_sleep_pin: GPIO32
  deep_sleep_delay: 1000ms #Задержка перед сном для обновления экрана 
  sleep_time: "3600" # sec
  error_sleep_duration: "1200" # sec
  # img
  img_type: BINARY
  img_format: PNG
  img_url_setup_logo: http://raw.githubusercontent.com/kfattum/esphome-trmnl/refs/heads/main/img/setup-logo.bmp
  # eink_display
  cs_pin: GPIO15
  dc_pin: GPIO27
  busy_pin: GPIO25
  reset_pin: GPIO26   
  reset_duration: 200 ms
  model: 7.50in-bV3       #✅7.50in-bV2 ✅7.50in-bV3 ❌7.50in-bV3-bwr(много ест оперативки)
  # spi
  clk_pin: GPIO13
  mosi_pin: GPIO14

globals:
  - id: device_id
    type: std::string
    max_restore_data_length: 13
    restore_value: true
    initial_value: '""' # bold-eagle-15
  - id: api_key
    type: std::string
    max_restore_data_length: 43
    restore_value: true
    initial_value: '""' # MnVGqCNfGhUPaDzJQMo24EFpSn12VaJh4DBRzztOpIw
  - id: sleep_time
    type: uint32_t
    restore_value: true
    initial_value: "$sleep_time"
  - id: current_page_id
    type: uint8_t
    restore_value: true
    initial_value: "0" # 0: нет данных, 1: trmnl_page, 2: failed, 3: pause_page

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf
  cpu_frequency: 240MHz

esphome:
  min_version: 2026.1.3 #https://github.com/esphome/esphome/pull/13599
  name: $name
  friendly_name: $friendly_name
  # platformio_options:
  #   board_build.f_flash: 80000000L
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  # name_add_mac_suffix: true
  # Dynamically set QR Code value for connecting to captive portal
  on_boot:
    priority: -10
    then:
      - delay: 15s # Даем время на попытку подключения
      - if:
          condition:
            not:
              wifi.connected:
          then:
            - script.execute: trmnl_error
  #   - priority: 600
  #     then:
  #       - lambda: |-
  #           id(wifi_connect_qr).set_value("WIFI:T:nopass;S:" + App.get_name() + ";;");
  # This will allow for project identification,
  # configuration and updates.
  # project:
  #   name: jesserockz.trmnl
  #   version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
# dashboard_import:
#   package_import_url: github://jesserockz/esphome-trmnl/trmnl.yaml@main

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
# esp32_improv:
#   authorizer: none

# To be able to get logs from the device via serial and api.
logger:
  on_message:
    level: ERROR
    then:
      - script.execute: trmnl_error

# Example configuration entry
mqtt:
  broker: $mqtt_broker_ip
  username: $name
  password: !secret mqtt_password
  on_connect:
    - delay: 500ms
    # - component.update: battery_voltage
    # - component.update: wifi_signal_db
    - if:
        condition:
          lambda: |-
            return id(device_id).empty() || id(api_key).empty();
        then:
          - script.execute: trmnl_setup
        else:
          - script.execute: trmnl_update

  # birth_message:
  #   topic: trmnl/status
  #   payload:
  # will_message:
  #   topic: trmnl/status
  #   payload: 

# ota:
#   - platform: esphome
#     password: !secret ota_password
    
mdns:
  disabled: true
# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  power_save_mode: LIGHT
  fast_connect: true # -5 сек
  output_power: 8.5dB
  manual_ip: 
    static_ip: $manual_ip_static_ip  # -3 сек 
    gateway: $manual_ip_gateway
    subnet: $manual_ip_subnet

          
  # Включите резервную точку доступа (captive portal) на случай сбоя Wi-Fi-соединения
  # ap:
  #   ssid: $name
  #   password: !secret hotspot_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
# captive_portal:

http_request:
  buffer_size_tx: 2048
  verify_ssl: False
  timeout: 10s
  watchdog_timeout: 15s

deep_sleep:
  wakeup_pin:
    number: $deep_sleep_pin
    allow_other_uses: true  
    inverted: true 
  run_duration: 2 min
  sleep_duration: $error_sleep_duration s

online_image:
  - id: trmnl_image
    format: $img_format
    type: $img_type
    buffer_size: 20000
    url: $img_url_setup_logo
    resize: 800x480
    on_download_finished:
      - delay: 16ms
      - script.execute:
          id: safe_update_display
          target_page: 1
          force_update: true 
    on_error:
        - script.execute: trmnl_error

script:

# /api/setup
# {
#     "api_key": "...",
#     "friendly_id": "...",
#     "image_url": "https://usetrmnl.com/images/setup/setup-logo.bmp",
#     "message": "Register at usetrmnl.com/signup with Device ID '...'",
#     "status": 200
# }

  - id: trmnl_setup
    then:
      - logger.log: "Setting up TRMNL"
      - http_request.get:
          url: ${server_url}/api/setup/
          request_headers:
            ID: !lambda 'return id(mac_address_sensor).state.c_str();'
          capture_response: true
          on_response:
            - if:
                condition:
                  lambda: return response->status_code >= 200 && response->status_code < 300;
                then:
                  - logger.log:
                      format: "TRMNL Setup Response: %s"
                      args: [body.c_str()]
                  - lambda: |-
                      json::parse_json(body, [](JsonObject root) -> bool {
                        // ArduinoJson 7: проверяем существование ключа и сразу его тип
                        if (root["api_key"].is<std::string>()) {
                          id(api_key) = root["api_key"].as<std::string>();
                          id(device_id) = root["friendly_id"].as<std::string>();
                          global_preferences->sync();
                        }
                        return true;
                      });
                  - delay: 16ms
                  - script.execute: trmnl_update
                else:
                  - logger.log:
                      format: "TRMNL Setup Failed. HTTP Status: %d"
                      args: [response->status_code]
                  - script.execute: trmnl_error
          on_error:
            - logger.log: "TRMNL Setup Connection Error / Timeout"
            - script.execute: trmnl_error

# curl http://192.168.1.123:80/api/display --header "access-token:xxxxxxxxxxxxxxxxxxxxxx"
# Invoke-WebRequest -Uri "http://192.168.1.123:80/api/display" -Headers @{"access-token"="MnVGqCNfGhUPaDzJQMo24EFpSn12VaJh4DBRzztOpIw"}

# /api/display
# {
#     "filename": "....bmp",
#     "firmware_url": "https://trmnl.s3.us-east-2.amazonaws.com/FW1.4.5.bin",
#     "image_url": "https://trmnl.s3.us-east-2.amazonaws.com/...",
#     "refresh_rate": 903,
#     "reset_firmware": false,
#     "special_function": "identify",
#     "status": 0,
#     "update_firmware": null
# }

  - id: trmnl_update
    then:
      - if:
          condition:
            switch.is_on: block_update_switch
          then:
            - logger.log: "Обновление дисплея заблокировано переключателем. Уходим в сон."
            - script.execute:
                id: safe_update_display
                target_page: 3 # ID страницы pause_page
                force_update: false
            - delay: $deep_sleep_delay
            - deep_sleep.enter:
                sleep_duration: $sleep_time s
          else:
            - logger.log: "Updating TRMNL image"
            - http_request.get:
                url: ${server_url}/api/display/
                request_headers:
                  ID: !lambda 'return id(mac_address_sensor).state.c_str();'
                  Access-Token: !lambda 'return id(api_key).c_str();'
                  Battery-Voltage: !lambda 'return id(battery_voltage_text).state.c_str();'
                capture_response: true
                on_response:
                  - if:
                      condition:
                        lambda: return response->status_code >= 200 && response->status_code < 300;
                      then:
                        - logger.log:
                            format: "TRMNL Update Response: %s"
                            args: [body.c_str()]
                        - lambda: |-
                            json::parse_json(body, [](JsonObject root) -> bool {
                              if (root["status"].is<int>() && root["status"].as<int>() == 0) {
                                id(trmnl_image).set_url(root["image_url"].as<std::string>());
                                id(sleep_time) = root["refresh_rate"].as<uint32_t>();
                              }
                              return true;
                            });
                        - delay: 16ms
                        - component.update: trmnl_image
                      else:
                        - logger.log:
                            format: "TRMNL Update Failed. HTTP Status: %d"
                            args: [response->status_code]
                        - script.execute: trmnl_error
                on_error:
                  - logger.log: "TRMNL Update Connection Error / Timeout"
                  - script.execute: trmnl_error

  - id: trmnl_error
    then:
      - logger.log: "trmnl_error"
      - script.execute:
          id: safe_update_display
          target_page: 2 # ID страницы failed
          force_update: false
      - delay: $deep_sleep_delay
      - deep_sleep.enter:
          sleep_duration: $error_sleep_duration s

  - id: safe_update_display
    parameters:
      target_page: uint8_t
      force_update: bool
    then:
      - if:
          condition:
            or:
              - lambda: 'return id(current_page_id) != target_page;'
              - lambda: 'return force_update;'
          then:
            - delay: 16ms
            - lambda: |-
                id(current_page_id) = target_page; // Запоминаем/подтверждаем новую страницу
                if (target_page == 1) {
                  id(trmnl_display).show_page(id(trmnl_page));
                  ESP_LOGD("display", "Обновление экрана: trmnl_page");
                } else if (target_page == 2) {
                  id(trmnl_display).show_page(id(failed));
                  ESP_LOGD("display", "Обновление экрана: failed");
                } else if (target_page == 3) {
                  id(trmnl_display).show_page(id(pause_page));
                  ESP_LOGD("display", "Обновление экрана: pause_page");
                }
            - delay: 16ms
            - component.update: trmnl_display
            - delay: $deep_sleep_delay
            - deep_sleep.enter:
                sleep_duration: $sleep_time s #!lambda 'return id(sleep_time) * 1000;'

          else:
            - logger.log: "Экран уже отображает эту страницу, перерисовка пропущена."

spi:
  clk_pin: $clk_pin
  mosi_pin: $mosi_pin

display:
  platform: waveshare_epaper
  id: trmnl_display
  cs_pin: $cs_pin
  dc_pin: $dc_pin
  busy_pin: 
    number: $busy_pin
    inverted: true #Для предотвращения необратимого повреждения дисплея необходимо инвертировать контакт BUSY на моделях gdew0154m09, Waveshare 7.30in-f и Waveshare 7.50in V2 (и наверно на V3 и других новых моделях). Установите для контакта busy значение inverted: true в настройках
  reset_pin: $reset_pin
  reset_duration: $reset_duration
  model: $model
  update_interval: never
  pages:
    - id: trmnl_page
      lambda: |-
        it.image(0, 0, id(trmnl_image), COLOR_OFF, COLOR_ON);

    - id: failed
      lambda: |-
        it.fill(COLOR_OFF);

    - id: pause_page
      lambda: |-
        it.fill(COLOR_ON);

button:
  - platform: factory_reset
    name: "Factory Reset"
    id: factory_reset_button

  - platform: restart
    name: "Перезагрузка"
    id: restart_button


binary_sensor:

  - platform: gpio
    name: Button
    id: back_button
    pin:
      number: GPIO32
      mode:
        input: true
        pullup: true
      allow_other_uses: true  
      inverted: true
    internal: True
    on_multi_click:
      - timing:
          - ON for at least 3s
          - OFF for at least 0.5s
        then:
          - button.press: factory_reset_button

      - timing:
          - ON for at least 0.3s
          - OFF for at least 0.5s
        then:
          - button.press: restart_button
    
sensor:
  - platform: adc
    name: "Напряжение батареи"
    icon: "mdi:alpha-v-cirde"
    entity_category: "diagnostic"
    id: battery_voltage
    pin: $adc_pin
    attenuation: 12db
    samples: 128
    # sampling_mode: min
    filters:
      - multiply: 2
      - round: 2
      # - calibrate_linear:
      #     - 0.0 -> 0.0
      #     - 3.70 -> 4.143
      #     - 3.86 -> 4.157 усб
    on_value:
      - text_sensor.template.publish:
          id: battery_voltage_text
          state: !lambda 'return str_sprintf("%.2f", x).c_str();'
      - mqtt.publish:
          topic: "$name/sensor/battery_voltage/state"
          payload: !lambda 'return to_string(x);'
          retain: true
    internal: true 

  - platform: copy
    id: battery_voltage_prc
    name: "Уровень заряда батареи"
    source_id: battery_voltage
    unit_of_measurement: "%"
    icon: "mdi:battery"
    device_class: battery
    state_class: measurement
    filters:
      - calibrate_linear:
          - 4.20 -> 100
          - 4.19 -> 99
          - 3.75 -> 80
          - 3.50 -> 20
          - 3.00 -> 0
      - round: 0
      - clamp:
          min_value: 0
          max_value: 100
    accuracy_decimals: 0
    internal: true 
    on_value:
      then:
        - mqtt.publish:
            topic: "$name/sensor/battery_voltage_prc/state"
            payload: !lambda 'return to_string(x);'
            retain: true

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "Сигнал Wi-Fi, dB"
    id: wifi_signal_db
    update_interval: never
    entity_category: "diagnostic"
    disabled_by_default: true
    internal: true 
    on_value:
      then:
        - mqtt.publish:
            topic: "$name/sensor/wifi_signal_db/state"
            payload: !lambda 'return to_string(x);'
            retain: true

  - platform: copy # Reports the WiFi signal strength in %
    id: wifi_signal_db_prc
    source_id: wifi_signal_db
    name: "Сигнал Wi-Fi"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
    internal: true 
    on_value:
      then:
        - mqtt.publish:
            topic: "$name/sensor/wifi_signal_db_prc/state"
            payload: !lambda 'return to_string(x);'
            retain: true
    
text_sensor:
  - platform: wifi_info
    mac_address:
      id: mac_address_sensor
  - platform: template
    id: battery_voltage_text
    update_interval: never

switch:
  - platform: template
    name: "Блокировка обновления дисплея"
    id: block_update_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF # По умолчанию блокировка выключена
    icon: "mdi:monitor-off"
    entity_category: config
